site_name: "python-app-2"
site_description: "Main documentation for the python-app-2"
repo_url: https://github.com/DaniloMirandaNG/python-app-2
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: "docs/index.md"
